//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PART1_ASP.NET {
    
    
    public partial class _4_3วิธีการใช้งานภาษา_JavaScript_ในหน้าเว็บเพจ__JavaScriptInline_html_ {
    }
}
